use_frameworks!

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'MGPlayerView_Example' do
  pod 'MGPlayerView', :path => '../'

  target 'MGPlayerView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
