use_frameworks!
platform :ios, '9.0'

target 'MGPlayerView_Example' do
  pod 'MGPlayerView', :path => '../'

  target 'MGPlayerView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
